### ISSUE TITLE
Default Scope (feature request)

### ISSUE THREAD

**Issue by Siddley** [agibsonsw/HTMLAttributes#1]
Hi, just wondering if you would be willing to change the default scope on your excellent attributes package.

Currently you have the scope as "text.html.basic meta.tag" and I am requesting that you widen the scope to "text.html meta.tag"

The issue is that I  (and perhaps others) use a custom html language def such as "text.html.enhanced" and your completions will not work for us until we manually edit the scope.

By widening your scope setting, you will not disturb anyone using text.html.basic, but you will help us with custom defs.

Thanks!

**Comment by agibsonsw** [comment]
No problem, just done. Andy.

**Comment by Siddley** [comment]
Awesome, thanks very much Andy!
