### ISSUE TITLE
Automatically Display Completions

### ISSUE THREAD

**Issue by kcrwfrd** [agibsonsw/HTMLAttributes#3]
Is there a way for it to automatically display completions, instead of having to press Ctrl+Space? My "auto_complete" setting is already set to "true", and sublime's default tag completion displays automatically, but not the attribute completion.

Thanks!

**Comment by agibsonsw** [comment]
Hello. This is probably possible with a combination of settings, but is not really my intent with this plug-in. As long as "auto_complete_commit_on_tab": true, then you can type just one or two letters and press TAB to jump into the attribute's value. For example, type 'su' then Tab will jump into summary="|"; type your text and press Tab to jump out. 'i' for 'id', 'v' for value, etc. In you are not familiar with the attribute-names then, of course, continue to use Ctrl-Space until you become familiar with them. Hope this helps!

**Comment by kcrwfrd** [comment]
Ah, I did not realize it would autocomplete even though the dialog isn't showing. That works well enough, it just seems inconsistent with other autocomplete behaviors in Sublime. If I get a moment, I'll try to look into how such an option could be added.

**Comment by agibsonsw** [comment]
Hello.

I think it should be possible to do this by adjusting settings. It may
require tweaking of the scope rule in the completions file as well.

I'm not keen, though, on modifying my Package to achieve this. I'm very
happy with it 'as is', as I can whiz through the attributes with no
interruption!

However, if you achieve this, could you let me know how and I could add it
to the readme as a consideration.

Regards, Andy.
