### ISSUE TITLE
Works only with div element...

### ISSUE THREAD

**Issue by PixelT** [agibsonsw/HTMLAttributes#6]
Hi,

The plugin works only with <div |> elements (| is caret)...
I tryed to ignore all others plugins - they still doesn't work 

Could you look at this / fix it?

**Comment by agibsonsw** [comment]
I do not have this issue and no one else has reported it (there have been thousands of downloads).

Unless others confirm the same issue, or you can provide precise details to replicate the issue, then I have to consider it an issue to do with your ST configuration. I'll re-open the issue if others confirm it.
